# Generated by Django 5.0.1 on 2024-01-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_winner_alter_user_won_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='comment',
        ),
    ]
